// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Capra"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Health",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StatusResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "ユーザを作成する。ユーザ情報はfirebase tokenから取得する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "[MEM-API-002] ユーザ情報登録",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "ユーザ情報を論理削除する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "[MEM-API-004] ユーザ退会",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "(公開用)ユーザID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/agreements": {
            "get": {
                "description": "指定したユーザの規約同意状況を参照する。ユーザ情報はヘッダから取得する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "[MEM-API-005] ユーザ規約同意状況参照",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetUserAgreementsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "指定したユーザの規約同意状況を更新する。ユーザ情報はヘッダから取得する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "[MEM-API-006] ユーザ規約同意状況更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "規約同意更新",
                        "name": "Policies",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserAgreementsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "put": {
                "description": "ユーザログイン処理を実施する。Ph0では公開用ユーザIDを返却するだけ。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "[MEM-API-007]ユーザログイン",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AgreementPolicyRequest": {
            "type": "object",
            "required": [
                "policy_id",
                "version"
            ],
            "properties": {
                "policy_id": {
                    "description": "規約ID",
                    "type": "string",
                    "example": "privacy_policy"
                },
                "version": {
                    "description": "規約バージョン",
                    "type": "string",
                    "example": "1.4"
                }
            }
        },
        "dto.CreateUserResponse": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "user_id": {
                    "description": "公開用ユーザID(28文字固定ULID）",
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.GetUserAgreementsResponse": {
            "type": "object",
            "properties": {
                "agreements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UserAgreementResponse"
                    }
                }
            }
        },
        "dto.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateUserAgreementsRequest": {
            "type": "object",
            "required": [
                "policies"
            ],
            "properties": {
                "policies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AgreementPolicyRequest"
                    }
                }
            }
        },
        "dto.UserAgreementResponse": {
            "type": "object",
            "required": [
                "agreed_version",
                "label",
                "latest_version",
                "policy_id",
                "status"
            ],
            "properties": {
                "agreed_version": {
                    "description": "同意バージョン",
                    "type": "string",
                    "example": "1.0"
                },
                "label": {
                    "description": "規約ラベル（表示名）",
                    "type": "string",
                    "example": "プライバシーポリシー"
                },
                "latest_version": {
                    "description": "最新バージョン",
                    "type": "string",
                    "example": "1.2"
                },
                "policy_id": {
                    "description": "規約ID",
                    "type": "string",
                    "example": "privacy_policy"
                },
                "status": {
                    "description": "同意ステータス",
                    "type": "string",
                    "example": "update_required"
                }
            }
        },
        "dto.UserLoginResponse": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "user_id": {
                    "description": "公開用ユーザID（28文字固定ULID）",
                    "type": "string",
                    "example": "001JSUFP94SNN~"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080/api/v0",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "JemRef Beta API",
	Description:      "JemRef backend API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
