// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Capra"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Health",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StatusResponse"
                        }
                    }
                }
            }
        },
        "/records": {
            "get": {
                "description": "ユーザに紐づく書誌情報をリストで返却する。ユーザ情報はfirebase tokenから取得する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "records"
                ],
                "summary": "[REF-API-001] 書誌一覧参照",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "名前（検索用：部分一致）",
                        "name": "contributerName",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "example": 50,
                        "description": "リミット",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "example": 20,
                        "description": "オフセット",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2026",
                        "description": "出版年（検索用）",
                        "name": "publish_year",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "publish_yaer",
                        "example": "insert_date",
                        "description": "並びかえキー (出版年、登録日)",
                        "name": "sort_key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "asc",
                        "example": "desc",
                        "description": "並び順（asc または desc）",
                        "name": "sort_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "音楽",
                        "description": "タイトル（検索用：主題または副題の部分一致）",
                        "name": "title",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetRecordsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "ユーザに紐づく書誌情報を登録する。ユーザ情報はfirebase tokenから取得する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "records"
                ],
                "summary": "[REF-API-003] 書誌情報登録",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "書誌情報登録リクエスト",
                        "name": "record",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateRecordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/records/{id}": {
            "get": {
                "description": "ユーザに紐づく書誌詳細情報を１件返却する。ユーザ情報はfirebase tokenから取得する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "records"
                ],
                "summary": "[REF-API-002] 書誌詳細参照",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ユーザ書誌ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetRecordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "ユーザに紐づく書誌情報を更新する。ユーザ情報はfirebase tokenから取得する。\u003cbr\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "records"
                ],
                "summary": "[REF-API-004] 書誌情報更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ユーザ書誌ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "書誌情報更新リクエスト",
                        "name": "Policies",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "ユーザに紐づく書誌情報を論理削除する。ユーザ情報はfirebase tokenから取得する。\u003cbr\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "records"
                ],
                "summary": "[REF-API-005] 書誌情報削除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ユーザ書誌ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "ユーザを作成する。ユーザ情報はfirebase tokenから取得する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "[MEM-API-002] ユーザ情報登録",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/agreements": {
            "get": {
                "description": "指定したユーザの規約同意状況を参照する。ユーザ情報はヘッダから取得する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "[MEM-API-005] ユーザ規約同意状況参照",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetUserAgreementsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "指定したユーザの規約同意状況を更新する。ユーザ情報はヘッダから取得する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "[MEM-API-006] ユーザ規約同意状況更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "規約同意更新リクエスト",
                        "name": "policies",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserAgreementsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "put": {
                "description": "ユーザログイン処理を実施する。Ph0では公開用ユーザIDを返却するだけ。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "[MEM-API-007]ユーザログイン",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "delete": {
                "description": "ユーザ情報を論理削除する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "[MEM-API-004] ユーザ退会",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cfirebase_id_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "(公開用)ユーザID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AgreementPolicyRequest": {
            "type": "object",
            "required": [
                "policy_id",
                "version"
            ],
            "properties": {
                "policy_id": {
                    "description": "規約ID",
                    "type": "string",
                    "example": "privacy_policy"
                },
                "version": {
                    "description": "規約バージョン",
                    "type": "string",
                    "example": "1.4"
                }
            }
        },
        "dto.ContainerDetailItem": {
            "type": "object",
            "properties": {
                "contributers": {
                    "description": "貢献者情報",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ContributerInfo"
                    }
                },
                "issue": {
                    "description": "号",
                    "type": "string",
                    "example": "第11号"
                },
                "main_title": {
                    "description": "主題",
                    "type": "string",
                    "example": "第1章 「学校」制度の境界線"
                },
                "option_value": {
                    "description": "オプション書誌項目値情報",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.OptionValues"
                        }
                    ]
                },
                "read_status": {
                    "description": "既読ステータス",
                    "type": "string",
                    "enum": [
                        "unread",
                        "reading",
                        "partially_read",
                        "read"
                    ]
                },
                "sub_title": {
                    "description": "副題",
                    "type": "string",
                    "example": "その形成と展開"
                },
                "volume": {
                    "description": "巻",
                    "type": "string",
                    "example": "日本教育史講座第1巻"
                }
            }
        },
        "dto.ContainerListItem": {
            "type": "object",
            "properties": {
                "contributers": {
                    "description": "収録物貢献者情報",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ContributerInfo"
                    }
                },
                "issue": {
                    "description": "号",
                    "type": "string",
                    "example": "第11号"
                },
                "main_title": {
                    "description": "収録物主題",
                    "type": "string",
                    "example": "境界線の学校史"
                },
                "sub_title": {
                    "description": "収録物副題",
                    "type": "string",
                    "example": "戦後日本の学校か社会の周辺と周縁"
                },
                "volume": {
                    "description": "巻",
                    "type": "string",
                    "example": "日本教育史講座第1巻"
                }
            }
        },
        "dto.ContributerInfo": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "木村元"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "author",
                        "interpreter",
                        "compiler",
                        "compiler_author"
                    ]
                }
            }
        },
        "dto.CreateRecordRequest": {
            "type": "object",
            "required": [
                "main_title",
                "type"
            ],
            "properties": {
                "container": {
                    "description": "収録物詳細情報",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.ContainerDetailItem"
                        }
                    ]
                },
                "contributers": {
                    "description": "貢献者情報",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ContributerInfo"
                    }
                },
                "main_title": {
                    "description": "主題",
                    "type": "string",
                    "example": "第1章 「学校」制度の境界線"
                },
                "memos": {
                    "description": "メモ情報",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.MemoInfo"
                    }
                },
                "option_value": {
                    "description": "オプション書誌項目値情報",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.OptionValues"
                        }
                    ]
                },
                "page_range": {
                    "description": "ページ数",
                    "type": "string",
                    "example": "15-46"
                },
                "publication_date": {
                    "description": "出版年（月日）",
                    "type": "string",
                    "example": "2022-11-30"
                },
                "publisher": {
                    "description": "出版社/出版者",
                    "type": "string",
                    "example": "東京大学出版会"
                },
                "read_status": {
                    "description": "既読ステータス",
                    "type": "string",
                    "enum": [
                        "unread",
                        "reading",
                        "partially_read",
                        "read"
                    ]
                },
                "sub_title": {
                    "description": "副題",
                    "type": "string",
                    "example": "その形成と展開"
                },
                "type": {
                    "description": "書誌タイプ",
                    "type": "string",
                    "enum": [
                        "monograph",
                        "journal_article",
                        "compilation_article"
                    ]
                },
                "urls": {
                    "description": "URL情報",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UrlInfo"
                    }
                }
            }
        },
        "dto.CreateRecordResponse": {
            "type": "object",
            "required": [
                "record_id",
                "user_id"
            ],
            "properties": {
                "record_id": {
                    "description": "公開用ユーザID",
                    "type": "string"
                },
                "user_id": {
                    "description": "公開用ユーザID（26桁固定ULID）",
                    "type": "string"
                }
            }
        },
        "dto.CreateUserResponse": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "user_id": {
                    "description": "公開用ユーザID(26文字固定ULID）",
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.GetRecordResponse": {
            "type": "object",
            "required": [
                "main_title",
                "record_id",
                "type"
            ],
            "properties": {
                "container": {
                    "description": "収録物詳細情報",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.ContainerDetailItem"
                        }
                    ]
                },
                "contributers": {
                    "description": "貢献者情報",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ContributerInfo"
                    }
                },
                "main_title": {
                    "description": "主題",
                    "type": "string",
                    "example": "第1章 「学校」制度の境界線"
                },
                "memos": {
                    "description": "メモ情報",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.MemoInfo"
                    }
                },
                "option_value": {
                    "description": "オプション書誌項目値情報",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.OptionValues"
                        }
                    ]
                },
                "page_range": {
                    "description": "ページ数",
                    "type": "string",
                    "example": "15-46"
                },
                "publication_date": {
                    "description": "出版年（月日）",
                    "type": "string",
                    "example": "2022-11-30"
                },
                "publisher": {
                    "description": "出版社/出版者",
                    "type": "string",
                    "example": "東京大学出版会"
                },
                "read_status": {
                    "description": "既読ステータス",
                    "type": "string",
                    "enum": [
                        "unread",
                        "reading",
                        "partially_read",
                        "read"
                    ]
                },
                "record_id": {
                    "description": "ユーザ書誌ID(36桁固定文字列)",
                    "type": "string",
                    "example": "AHIF98DJ0SJUFY874H..."
                },
                "sub_title": {
                    "description": "副題",
                    "type": "string",
                    "example": "その形成と展開"
                },
                "type": {
                    "description": "書誌タイプ",
                    "type": "string",
                    "enum": [
                        "monograph",
                        "journal_article",
                        "compilation_article"
                    ]
                },
                "urls": {
                    "description": "URL情報",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UrlInfo"
                    }
                }
            }
        },
        "dto.GetRecordsResponse": {
            "type": "object",
            "required": [
                "count",
                "records"
            ],
            "properties": {
                "count": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.RecordListItemResponse"
                    }
                }
            }
        },
        "dto.GetUserAgreementsResponse": {
            "type": "object",
            "properties": {
                "agreements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UserAgreementResponse"
                    }
                }
            }
        },
        "dto.MemoInfo": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "メモの内容",
                    "type": "string",
                    "example": "学校の戦後史。少し難しい。"
                },
                "label": {
                    "description": "ラベル",
                    "type": "string",
                    "example": "要約"
                }
            }
        },
        "dto.OptionValues": {
            "type": "object",
            "properties": {
                "edition": {
                    "type": "string",
                    "example": "第２版"
                },
                "isbn": {
                    "type": "string",
                    "example": "9784130513555"
                },
                "original_title": {
                    "type": "string",
                    "example": "History of School of Boundary"
                }
            }
        },
        "dto.RecordListItemResponse": {
            "type": "object",
            "required": [
                "main_title",
                "record_id",
                "type"
            ],
            "properties": {
                "container": {
                    "description": "収録物情報",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.ContainerListItem"
                        }
                    ]
                },
                "contributers": {
                    "description": "貢献者情報",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ContributerInfo"
                    }
                },
                "main_title": {
                    "description": "主題",
                    "type": "string",
                    "example": "第1章 「学校」制度の境界線"
                },
                "page_range": {
                    "description": "ページ数",
                    "type": "string",
                    "example": "15-46"
                },
                "publication_date": {
                    "description": "出版年（月日）",
                    "type": "string",
                    "example": "2022-11-30"
                },
                "publisher": {
                    "description": "出版社/出版者",
                    "type": "string",
                    "example": "東京大学出版会"
                },
                "read_status": {
                    "description": "既読ステータス",
                    "type": "string",
                    "enum": [
                        "unread",
                        "reading",
                        "partially_read",
                        "read"
                    ]
                },
                "record_id": {
                    "description": "ユーザ書誌ID(36桁固定文字列)",
                    "type": "string",
                    "example": "AHIF98DJ0SJUFY874H..."
                },
                "sub_title": {
                    "description": "副題",
                    "type": "string",
                    "example": "その形成と展開"
                },
                "type": {
                    "description": "書誌タイプ",
                    "type": "string",
                    "enum": [
                        "monograph",
                        "journal_article",
                        "compilation_article"
                    ]
                }
            }
        },
        "dto.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateRecordRequest": {
            "type": "object",
            "required": [
                "main_title",
                "type"
            ],
            "properties": {
                "container": {
                    "description": "収録物詳細情報",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.ContainerDetailItem"
                        }
                    ]
                },
                "contributers": {
                    "description": "貢献者情報",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ContributerInfo"
                    }
                },
                "main_title": {
                    "description": "主題",
                    "type": "string",
                    "example": "第1章 「学校」制度の境界線"
                },
                "memos": {
                    "description": "メモ情報",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.MemoInfo"
                    }
                },
                "option_value": {
                    "description": "オプション書誌項目値情報",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.OptionValues"
                        }
                    ]
                },
                "page_range": {
                    "description": "ページ数",
                    "type": "string",
                    "example": "15-46"
                },
                "publication_date": {
                    "description": "出版年（月日）",
                    "type": "string",
                    "example": "2022-11-30"
                },
                "publisher": {
                    "description": "出版社/出版者",
                    "type": "string",
                    "example": "東京大学出版会"
                },
                "read_status": {
                    "description": "既読ステータス",
                    "type": "string",
                    "enum": [
                        "unread",
                        "reading",
                        "partially_read",
                        "read"
                    ]
                },
                "sub_title": {
                    "description": "副題",
                    "type": "string",
                    "example": "その形成と展開"
                },
                "type": {
                    "description": "書誌タイプ",
                    "type": "string",
                    "enum": [
                        "monograph",
                        "journal_article",
                        "compilation_article"
                    ]
                },
                "urls": {
                    "description": "URL情報",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UrlInfo"
                    }
                }
            }
        },
        "dto.UpdateUserAgreementsRequest": {
            "type": "object",
            "required": [
                "policies"
            ],
            "properties": {
                "policies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AgreementPolicyRequest"
                    }
                }
            }
        },
        "dto.UrlInfo": {
            "type": "object",
            "properties": {
                "label": {
                    "description": "ラベル",
                    "type": "string",
                    "example": "オンラインPDFのリンク"
                },
                "value": {
                    "description": "URL",
                    "type": "string",
                    "example": "https://example.com/sample"
                }
            }
        },
        "dto.UserAgreementResponse": {
            "type": "object",
            "required": [
                "agreed_version",
                "label",
                "latest_version",
                "policy_id",
                "status"
            ],
            "properties": {
                "agreed_version": {
                    "description": "同意バージョン",
                    "type": "string",
                    "example": "1.0"
                },
                "label": {
                    "description": "規約ラベル（表示名）",
                    "type": "string",
                    "example": "プライバシーポリシー"
                },
                "latest_version": {
                    "description": "最新バージョン",
                    "type": "string",
                    "example": "1.2"
                },
                "policy_id": {
                    "description": "規約ID",
                    "type": "string",
                    "example": "privacy_policy"
                },
                "status": {
                    "description": "同意ステータス",
                    "type": "string",
                    "example": "update_required"
                }
            }
        },
        "dto.UserLoginResponse": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "user_id": {
                    "description": "公開用ユーザID（26文字固定ULID）",
                    "type": "string",
                    "example": "001JSUFP94SNN~"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080/api/v0",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "JemRef Beta API",
	Description:      "JemRef backend API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
